/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function fromString(input: string): void
export function fromBufferToString(input: Buffer): void
export function fromBufferToStringSimd(input: Buffer): void
export function toBufferWithLength(len: number): Buffer
export function toStringWithLength(len: number): string
